#!/usr/bin/env bash
# ~/.bashrc

echo "[bash]: sourced file -- bashrc"

{ # SET ENV & SESSION VARS
	PS1='[\W]\$ '
	GLOBIGNORE=.DS_Store:.CFUserTextEncoding:.*.sw[a-z]
}

{ # SET SHELL OPTIONS
	shopt -s cdable_vars
}

{ # SET ALIASES
	alias sbash='[ -r ~/.bash_profile ] && . ~/.bash_profile'

	if [[ "$(uname -s)" == 'Darwin' ]];
	if _is_mac;
	then alias ls='ls -G'
	else alias ls='ls --color=auto'
	fi

	alias ls='ls -G'
	alias la='ls -A'
	alias ll='ls -l'
	alias lla='ls -lA'
	alias l1='ls -1'
	alias lm='ls -m'
	alias l.='ls -Ad .[^$\(.$\)]*'
	alias ll.='ls -Ald .[^$\(.$\)]*'

	alias code='/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code'
}
