#!/usr/bin/env bash
# ~/.bashrc

if [[ "$(uname)" == 'Darwin' ]]; then
	[[ -r "${BASH_INIT_FILES['darwin']}" ]] && source "${BASH_INIT_FILES['darwin']}"
fi

winproc () 
{ 
    while IFS=' 
' read -r NAME ID GROUP XX SIZE; do
        printf '\t[%s]: [%s] %s\n' "${NAME}" "${ID}" "${SIZE}";
    done < <(tasklist | tr '\t' ' ' | tr -s ' ' | sed -E -e 's/[[^::blank:]]*(.*)[[:blank:]]*$/\1/g' | sed 's/ K$/K/' | sed -E -e 's/,([0-9]+)/\1/');
    return
}
