#!/usr/bin/env zsh
# USER ZSH CONFIGURATION: ~/.zprofile

{	# HELPER FUNCTIONS

	_report_sourced () {
		local SOURCED_FILE;
		SOURCED_FILE="${1:?}";
		printf '  [zsh]: sourced file -- %s\n' "${SOURCED_FILE}";
		return;
	}
}

_report_sourced "~/.zprofile"
