#!/usr/bin/env zsh
# USER ZSH CONFIGURATION: ~/.zshrc

_report_sourced "~/.zshrc"

{	# HELPER FUNCTIONS AND VARIABLES

	_prepend_to_path () {
		local TARGET_PATH
		TARGET_PATH="${1:?}"
		! echo "${PATH}" | /usr/bin/grep -qe "${TARGET_PATH}" \
			&& export PATH="${TARGET_PATH}${PATH:+":$PATH"}"
		return
	}

	_is_mac () {
		[[ "$(uname -s)" == 'Darwin' ]]
		return $?
	}

	_is_linux () {
		[[ "$(uname -s)" == 'Linux' ]]
		return $?
	}

	declare -a PREPEND_PATHS
	PREPEND_PATHS=(
		~/.bin
	);
}


{	# SET PATH

	if _is_mac;
	then # set mac PATH variables

		# set homebrew vars
		eval "$(/opt/homebrew/bin/brew shellenv)"

		# set homebrew-installed python path
		declare PYTHON_EXEC_PATH
		PYTHON_EXEC_PATH='/opt/homebrew/opt/python@3.9/libexec/bin'
		[[ -d "${PYTHON_EXEC_PATH}" ]] \
			&& PREPEND_PATHS+=( "${PYTHON_EXEC_PATH}" )
	fi

	if (( ${#PREPEND_PATHS[@]} > 0 ));
	then
		for dir in "${PREPEND_PATHS[@]}";
		do
			# create dir if does not exist
			if [[ ! -d "${dir}" ]]; then
				printf '>> creating directory: %s... ' "${dir}"
				if mkdir "${dir}" &> /dev/null;
				then echo SUCCESS!
				else echo FAILED!; continue;
			fi
			_prepend_to_path "${dir}"
		done
	fi

	unset PYTHON_EXEC_PATH PREPEND_PATHS
}

{	# SET ENVIRONMENT VARIABLES
	export LSCOLORS='Gxcxcxdxbxegedabagacad'
}

{	# SET ALIASES

	if _is_mac; then alias ls='command ls -G'; fi
	elif _is_linux; then alias ls='command ls --color=auto'
	else alias ls='command ls --color=auto'
	fi

	alias l.='ls -d .[^(.$)$]*'
	alias la='ls -A'
	alias ld='ls -d .[^(.$)$]*'
	alias ll='ls -l'
	alias ll.='ls -ld .[^(.$)$]*'
	alias lla='ls -lA'
	alias l1='ls -1'
	alias lm='ls -m'
	alias l1.='ls -1d .[^(.$)$]*'
	alias lm.='ls -md .[^(.$)$]*'

	alias grep='command grep --color=auto'
	alias egrep='egrep --color=auto'
	alias fgrep='fgrep --color=auto'
}

