#!/usr/bin/env zsh
# USER ZSH CONFIGURATION: ~/.zshrc

_report_sourced "~/.zshrc"

{	# HELPER FUNCTIONS AND VARIABLES

	_prepend_to_path () {
		local TARGET_PATH
		TARGET_PATH="${1:?}"
		! echo "${PATH}" | /usr/bin/grep -qe "${TARGET_PATH}" \
			&& export PATH="${TARGET_PATH}${PATH:+":$PATH"}"
		return
	}

	_is_mac () {
		[[ "$(uname -s)" == 'Darwin' ]]
		return $?
	}

	declare -a PREPEND_PATHS
	PREPEND_PATHS=(
		~/.bin
	);
}


{	# SET PATH

	if _is_mac;
	then # set mac PATH variables

		# set homebrew vars
		eval "$(/opt/homebrew/bin/brew shellenv)"

		# set homebrew-installed python path
		declare PYTHON_EXEC_PATH
		PYTHON_EXEC_PATH='/opt/homebrew/opt/python@3.9/libexec/bin'
		[[ -d "${PYTHON_EXEC_PATH}" ]] \
			&& PREPEND_PATHS+=( "${PYTHON_EXEC_PATH}" )
	fi

	if (( ${#PREPEND_PATHS[@]} > 0 ));
	then
		for dir in "${PREPEND_PATHS[@]}";
		do _prepend_to_path "${dir}"
		done
	fi

	unset PYTHON_EXEC_PATH PREPEND_PATHS
}

{	# SET ENVIRONMENT VARIABLES
	export LSCOLORS='Gxcxcxdxbxegedabagacad'
}

